
services:
  postgres:
    image: postgres:15
    container_name: source-postgres
    environment:
      POSTGRES_DB: source_db
      POSTGRES_USER: source_user
      POSTGRES_PASSWORD: source_pass
    ports:
      - "5780:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: >
      postgres
      -c wal_level=logical
      -c max_replication_slots=10
      -c max_wal_senders=10
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U source_user"]
      interval: 10s
      timeout: 5s
      retries: 5

  faker-service:
    build: ./faker-service
    container_name: faker-service
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: source_db
      POSTGRES_USER: source_user
      POSTGRES_PASSWORD: source_pass

      INITIAL_LOAD_SIZE: 10000
      INSERT_BATCH_SIZE: 200
      UPDATE_BATCH_SIZE: 100
      SLEEP_SECONDS: 30
    restart: unless-stopped

  api-pdv:
    build: ./pdv-api
    container_name: pdv-api
    ports:
      - "8001:8001"
    depends_on:
      - redis

  cache-loader:
    build: ./cache-loader
    container_name: cache-loader
    depends_on:
      redis:
        condition: service_healthy # Só inicia o Python quando o Redis estiver pronto
    env_file:
      - .env  # Isso vai garantir que as variáveis do Snowflake sejam lidas
    environment:
      - PYTHONUNBUFFERED=1
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    restart: unless-stopped

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5


volumes:
  postgres_data:
